//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFVBNewTPV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=127.0.0.1;database=TPV;user=root")]
        public string CADENA_CONEXION {
            get {
                return ((string)(this["CADENA_CONEXION"]));
            }
            set {
                this["CADENA_CONEXION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("osk.exe")]
        public string PROGRAMA_TECLADO {
            get {
                return ((string)(this["PROGRAMA_TECLADO"]));
            }
            set {
                this["PROGRAMA_TECLADO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MODO_DEBUG {
            get {
                return ((bool)(this["MODO_DEBUG"]));
            }
            set {
                this["MODO_DEBUG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R18")]
        public string COD_IVA_DEF {
            get {
                return ((string)(this["COD_IVA_DEF"]));
            }
            set {
                this["COD_IVA_DEF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ACTIVAR_BARRA_BUSQ_RAP {
            get {
                return ((bool)(this["ACTIVAR_BARRA_BUSQ_RAP"]));
            }
            set {
                this["ACTIVAR_BARRA_BUSQ_RAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1001000000")]
        public long CLIENTE_DEFECTO {
            get {
                return ((long)(this["CLIENTE_DEFECTO"]));
            }
            set {
                this["CLIENTE_DEFECTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPV_NUEVO_DESPUES_GUARDAR {
            get {
                return ((bool)(this["TPV_NUEVO_DESPUES_GUARDAR"]));
            }
            set {
                this["TPV_NUEVO_DESPUES_GUARDAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TICKET_IMP_DEF {
            get {
                return ((string)(this["TICKET_IMP_DEF"]));
            }
            set {
                this["TICKET_IMP_DEF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPV_PIST_LINEA_AUTO {
            get {
                return ((bool)(this["TPV_PIST_LINEA_AUTO"]));
            }
            set {
                this["TPV_PIST_LINEA_AUTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPV_LIN_AGRUPAR_LINEAS {
            get {
                return ((bool)(this["TPV_LIN_AGRUPAR_LINEAS"]));
            }
            set {
                this["TPV_LIN_AGRUPAR_LINEAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPV_TICK_IMPRCOBR {
            get {
                return ((bool)(this["TPV_TICK_IMPRCOBR"]));
            }
            set {
                this["TPV_TICK_IMPRCOBR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPV_DOC_GUARDARCOBR {
            get {
                return ((bool)(this["TPV_DOC_GUARDARCOBR"]));
            }
            set {
                this["TPV_DOC_GUARDARCOBR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TPV_COBR_COBROSCUENTE {
            get {
                return ((bool)(this["TPV_COBR_COBROSCUENTE"]));
            }
            set {
                this["TPV_COBR_COBROSCUENTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPV_DOC_BLOQUEARANT {
            get {
                return ((bool)(this["TPV_DOC_BLOQUEARANT"]));
            }
            set {
                this["TPV_DOC_BLOQUEARANT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPV_DOC_GUARDASINLIQ {
            get {
                return ((bool)(this["TPV_DOC_GUARDASINLIQ"]));
            }
            set {
                this["TPV_DOC_GUARDASINLIQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPV_PROD_PERMITIR_SIN_EXISTENCIAS {
            get {
                return ((bool)(this["TPV_PROD_PERMITIR_SIN_EXISTENCIAS"]));
            }
            set {
                this["TPV_PROD_PERMITIR_SIN_EXISTENCIAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[APPBASE]\\IMGPROD\\")]
        public string PROD_RUTA_IMAGENES {
            get {
                return ((string)(this["PROD_RUTA_IMAGENES"]));
            }
            set {
                this["PROD_RUTA_IMAGENES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string TPV_TIPO_DOC_NUEVO_DEF {
            get {
                return ((string)(this["TPV_TIPO_DOC_NUEVO_DEF"]));
            }
            set {
                this["TPV_TIPO_DOC_NUEVO_DEF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TPV_USO_TECLAS_RAPIDAS {
            get {
                return ((bool)(this["TPV_USO_TECLAS_RAPIDAS"]));
            }
            set {
                this["TPV_USO_TECLAS_RAPIDAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WIN7_METODO_TECLADO {
            get {
                return ((bool)(this["WIN7_METODO_TECLADO"]));
            }
            set {
                this["WIN7_METODO_TECLADO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\xampp\\mysql\\bin\\mysqldump.exe")]
        public string MYSQDUMP_RUTA {
            get {
                return ((string)(this["MYSQDUMP_RUTA"]));
            }
            set {
                this["MYSQDUMP_RUTA"] = value;
            }
        }
    }
}
