ALTER TABLE `TPV`.`prod_productos` ADD COLUMN `IMAGEN_PROD` VARCHAR(60) NULL DEFAULT NULL  AFTER `EXISTENCIAS_PROD` ;
ALTER TABLE `TPV`.`lido_lineas_documento` CHANGE COLUMN `PVP_LIDO` `PVP_LIDO` DOUBLE ZEROFILL NULL DEFAULT 0 COMMENT 'Total del precio (pvp_lido*(1+porc_iva_lido))\n';
CREATE  TABLE IF NOT EXISTS `TPV`.`mspr_mov_stock_prod` (

  `ID_ELEM` BIGINT(20) NOT NULL ,

  `ID_ELEM_PROD` BIGINT(20) NOT NULL ,

  `FECHA_MOVIMIENTO_MSPR` DATETIME NULL DEFAULT NULL ,

  `ENTRADA_MSPR` DOUBLE NULL DEFAULT NULL ,

  `SALIDA_MSPR` DOUBLE NULL DEFAULT NULL ,

  `ID_ELEM_OPER` BIGINT(20) NULL DEFAULT NULL COMMENT 'Elemento que ha realizado la operacion sobre el stock' ,

  PRIMARY KEY (`ID_ELEM`, `ID_ELEM_PROD`) ,

  INDEX `FK_MSPR_PROD` (`ID_ELEM_PROD` ASC) ,

  INDEX `FK_MSPR_ELEM` (`ID_ELEM` ASC) ,

  INDEX `FK_MSPR_ELEM2` (`ID_ELEM_OPER` ASC) ,

  CONSTRAINT `FK_MSPR_PROD`

    FOREIGN KEY (`ID_ELEM_PROD` )

    REFERENCES `TPV`.`prod_productos` (`ID_ELEM` )

    ON DELETE NO ACTION

    ON UPDATE NO ACTION,

  CONSTRAINT `FK_MSPR_ELEM`

    FOREIGN KEY (`ID_ELEM` )

    REFERENCES `TPV`.`elem_elementos` (`ID_ELEMENTO` )

    ON DELETE NO ACTION

    ON UPDATE NO ACTION,

  CONSTRAINT `FK_MSPR_ELEM2`

    FOREIGN KEY (`ID_ELEM_OPER` )

    REFERENCES `TPV`.`elem_elementos` (`ID_ELEMENTO` )

    ON DELETE NO ACTION

    ON UPDATE NO ACTION)

ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8

COLLATE = utf8_general_ci

COMMENT = 'Movimientos de stokcs de los productos\n';

ALTER TABLE `TPV`.`lire_lin_reservas` DROP FOREIGN KEY `FK_LIRE_PROD`; 

ALTER TABLE `TPV`.`lire_lin_reservas` 

  ADD CONSTRAINT `FK_LIRE_PROD`

  FOREIGN KEY (`ID_ELEM_PROD` )

  REFERENCES `TPV`.`prod_productos` (`ID_ELEM` )

  ON DELETE NO ACTION

  ON UPDATE NO ACTION;
  
 ALTER TABLE `TPV`.`esre_estado_reservas` ADD COLUMN `DESCARGABLE` ENUM('S','N') NULL DEFAULT NULL  AFTER `DESCR_ESRE` 


