ALTER TABLE `TPV`.`lire_lin_reservas`
 ADD COLUMN `PVB_LIRE` DOUBLE NULL DEFAULT NULL  AFTER `CANTIDAD_PROD` ,
 ADD COLUMN `PORC_IVA_LIRE` DOUBLE NULL DEFAULT NULL  AFTER `PVB_LIRE` , 
 ADD COLUMN `PVP_LIRE` DOUBLE NULL DEFAULT NULL  AFTER `PORC_IVA_LIRE` , 
 ADD COLUMN `TOTAL_LIRE` DOUBLE NULL DEFAULT NULL  AFTER `PVP_LIRE`;